package com.mmtap.trader.janapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:900</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class BackupInfo extends Structure {
	/**
	 * file name<br>
	 * C type : char[256]
	 */
	public byte[] file = new byte[256];
	/** file size */
	public int size;
	/** Conversion Error : time_t (Primitive without known type for this runtime: NativeTime) */
	/**
	 * reserved<br>
	 * C type : int[6]
	 */
	public int[] reserved = new int[6];
	public BackupInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("file", "size", "reserved");
	}
	/**
	 * @param file file name<br>
	 * C type : char[256]<br>
	 * @param size file size<br>
	 * @param reserved reserved<br>
	 * C type : int[6]
	 */
	public BackupInfo(byte file[], int size, int reserved[]) {
		super();
		if ((file.length != this.file.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.file = file;
		this.size = size;
		if ((reserved.length != this.reserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserved = reserved;
	}
	public BackupInfo(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends BackupInfo implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends BackupInfo implements Structure.ByValue {
		
	};
}
