package com.mmtap.trader.janapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:160</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ConTime extends Structure {
	/**
	 * server's accessebility (7 days-24 hours, 0-denied, 1-allowed)<br>
	 * C type : int[7][24]
	 */
	public int[] days = new int[((7) * (24))];
	/** internal variable */
	public int dayscontrol;
	/**
	 * reserved<br>
	 * C type : int[3]
	 */
	public int[] reserved = new int[3];
	public ConTime() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("days", "dayscontrol", "reserved");
	}
	/**
	 * @param days server's accessebility (7 days-24 hours, 0-denied, 1-allowed)<br>
	 * C type : int[7][24]<br>
	 * @param dayscontrol internal variable<br>
	 * @param reserved reserved<br>
	 * C type : int[3]
	 */
	public ConTime(int days[], int dayscontrol, int reserved[]) {
		super();
		if ((days.length != this.days.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.days = days;
		this.dayscontrol = dayscontrol;
		if ((reserved.length != this.reserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserved = reserved;
	}
	public ConTime(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ConTime implements Structure.ByReference {
		
	};
	public static class ByValue extends ConTime implements Structure.ByValue {
		
	};
}
