package com.mmtap.trader.janapi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * ---<br>
 * <i>native declaration : MT4ManagerAPI.h:398</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class LiveInfoFile extends Structure {
	/**
	 * file name<br>
	 * C type : char[256]
	 */
	public byte[] file = new byte[256];
	/** file size */
	public int size;
	/**
	 * file hash<br>
	 * C type : char[36]
	 */
	public byte[] hash = new byte[36];
	/**
	 * reserved<br>
	 * C type : int[10]
	 */
	public int[] reserved = new int[10];
	public LiveInfoFile() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("file", "size", "hash", "reserved");
	}
	/**
	 * @param file file name<br>
	 * C type : char[256]<br>
	 * @param size file size<br>
	 * @param hash file hash<br>
	 * C type : char[36]<br>
	 * @param reserved reserved<br>
	 * C type : int[10]
	 */
	public LiveInfoFile(byte file[], int size, byte hash[], int reserved[]) {
		super();
		if ((file.length != this.file.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.file = file;
		this.size = size;
		if ((hash.length != this.hash.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.hash = hash;
		if ((reserved.length != this.reserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserved = reserved;
	}
	public LiveInfoFile(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends LiveInfoFile implements Structure.ByReference {
		
	};
	public static class ByValue extends LiveInfoFile implements Structure.ByValue {
		
	};
}
