package com.mmtap.trader.janapi;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1372</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class NewsTopic extends Structure {
	/** news key */
	public NativeLong key;
	/** Conversion Error : time_t (Primitive without known type for this runtime: NativeTime) */
	/**
	 * news source time ("yyyy/mm/dd hh:mm:ss")<br>
	 * C type : char[32]
	 */
	public byte[] ctm = new byte[32];
	/**
	 * news topic<br>
	 * C type : char[256]
	 */
	public byte[] topic = new byte[256];
	/**
	 * news category<br>
	 * C type : char[64]
	 */
	public byte[] category = new byte[64];
	/**
	 * news keywords<br>
	 * C type : char[256]
	 */
	public byte[] keywords = new byte[256];
	/**
	 * body (if present)<br>
	 * C type : char*
	 */
	public Pointer body;
	/** body length */
	public int bodylen;
	/** readed flag */
	public int readed;
	/** news priority: 0-general, 1-high */
	public int priority;
	/** news LANGID */
	public int langid;
	/** C type : int[1] */
	public int[] reserved = new int[1];
	public NewsTopic() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("key", "ctm", "topic", "category", "keywords", "body", "bodylen", "readed", "priority", "langid", "reserved");
	}
	public NewsTopic(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends NewsTopic implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends NewsTopic implements Structure.ByValue {
		
	};
}
