package com.mmtap.trader.janapi;
import com.mmtap.trader.janapi.MT4ManagerAPILibrary.COLORREF;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * ---<br>
 * <i>native declaration : MT4ManagerAPI.h:1330</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SymbolProperties extends Structure {
	/**
	 * symbol<br>
	 * C type : char[12]
	 */
	public byte[] symbol = new byte[12];
	/**
	 * symbol color<br>
	 * C type : COLORREF
	 */
	public COLORREF color;
	/** symbol spread */
	public int spread;
	/** spread balance */
	public int spread_balance;
	/** stops level */
	public int stops_level;
	/** smoothing */
	public int smoothing;
	/** execution mode */
	public int exemode;
	/**
	 * reserved<br>
	 * C type : int[8]
	 */
	public int[] reserved = new int[8];
	public SymbolProperties() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("symbol", "color", "spread", "spread_balance", "stops_level", "smoothing", "exemode", "reserved");
	}
	/**
	 * @param symbol symbol<br>
	 * C type : char[12]<br>
	 * @param color symbol color<br>
	 * C type : COLORREF<br>
	 * @param spread symbol spread<br>
	 * @param spread_balance spread balance<br>
	 * @param stops_level stops level<br>
	 * @param smoothing smoothing<br>
	 * @param exemode execution mode<br>
	 * @param reserved reserved<br>
	 * C type : int[8]
	 */
	public SymbolProperties(byte symbol[], COLORREF color, int spread, int spread_balance, int stops_level, int smoothing, int exemode, int reserved[]) {
		super();
		if ((symbol.length != this.symbol.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.symbol = symbol;
		this.color = color;
		this.spread = spread;
		this.spread_balance = spread_balance;
		this.stops_level = stops_level;
		this.smoothing = smoothing;
		this.exemode = exemode;
		if ((reserved.length != this.reserved.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.reserved = reserved;
	}
	public SymbolProperties(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SymbolProperties implements Structure.ByReference {
		
	};
	public static class ByValue extends SymbolProperties implements Structure.ByValue {
		
	};
}
