package com.mmtap.trader.janapi;
import com.mmtap.trader.janapi.MT4ManagerAPILibrary.UCHAR;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1095</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public abstract class TradeTransInfo extends Structure {
	/**
	 * trade transaction type<br>
	 * C type : UCHAR
	 */
	public UCHAR type;
	/** flags */
	public byte flags;
	/** trade command */
	public short cmd;
	/** order, order by */
	public int order;
	/** order, order by */
	public int orderby;
	/**
	 * trade symbol<br>
	 * C type : char[12]
	 */
	public byte[] symbol = new byte[12];
	/** trade volume */
	public int volume;
	/** trade price */
	public double price;
	/** stoploss, takeprofit */
	public double sl;
	/** stoploss, takeprofit */
	public double tp;
	/** deviation on IE */
	public int ie_deviation;
	/**
	 * comment<br>
	 * C type : char[32]
	 */
	public byte[] comment = new byte[32];
	/** Conversion Error : time_t (Primitive without known type for this runtime: NativeTime) */
	/** crc */
	public int crc;
	public TradeTransInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("type", "flags", "cmd", "order", "orderby", "symbol", "volume", "price", "sl", "tp", "ie_deviation", "comment", "crc");
	}
	public TradeTransInfo(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends TradeTransInfo implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends TradeTransInfo implements Structure.ByValue {
		
	};
}
