package com.mmtap.trader.janapi;
import com.mmtap.trader.janapi.MT4ManagerAPILibrary.UCHAR;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * +------------------------------------------------------------------+<br>
 * <i>native declaration : MT4ManagerAPI.h:1084</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class TradeRestoreResult extends Structure {
	/** order */
	public int order;
	/**
	 * RET_OK    - order restored<br>
	 * C type : UCHAR
	 */
	public UCHAR res;
	public TradeRestoreResult() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("order", "res");
	}
	/**
	 * @param order order<br>
	 * @param res RET_OK    - order restored<br>
	 * C type : UCHAR
	 */
	public TradeRestoreResult(int order, UCHAR res) {
		super();
		this.order = order;
		this.res = res;
	}
	public TradeRestoreResult(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TradeRestoreResult implements Structure.ByReference {
		
	};
	public static class ByValue extends TradeRestoreResult implements Structure.ByValue {
		
	};
}
